### ISSUE TITLE
[ramuda] Re-deploys version even without changes

### ISSUE THREAD

**Issue by ludwigm** [glomex/gcdt#145]
Ramuda has a feature to upload only the new code bundle when there are no changes. This only works locally when you keep the "vendored" folder which is not cleaned up. On a Continous Integration server with a clean environment for each deploy this breaks and every run new versions will be deployed. This will cause massive problems if we want to track errors to the business logic. It can be replicated locally with executing two times in a row "deploy". The second time it does not upload. You delete the vendored folder now and the do "deploy". It will re-upload.

**Comment by markfink** [comment]
Main issue is "works as designed". Every code bundle will have a different hashcode since it factors in timestamps unless the bundle was created from the same virtualenv. Only in this case unchanged code will result in bundles with the same hashcode.
We now implemented the '--keep' option for ramuda bundle and deploy.
We updated the ramuda documentation to make this behaviour more obvious.
A more technical (gcdt development) implication of this is that the automated tests for hascodes only works in placebo 'normal' and not in 'playback' mode.
