### ISSUE TITLE
[gcdt_slack_integration]Always success message for kumo and tenkai

### ISSUE THREAD

**Issue by Dgadavin** [glomex/gcdt#348]
We have always `SUCCESS` message in Slack even if deployment was failed. I tested `kumo` and `tenkai`

**Comment by markfink** [comment]
I could reproduce the described problem. The problem was that the command lifecycle did not feed back the commands exit_code into the commands context as 'error'. Consequently the gcdt-slack-integration plugin reported the wrong deployment status.

After the fix I recreated a situation like you described with a successful kumo deployment and a failing tenkai deployment:

![image](https://user-images.githubusercontent.com/33456/28815151-a80f1d3a-76a0-11e7-9f03-406c92edc1d0.png)

@Dgadavin again thank you for your analysis and reporting this.

**Comment by markfink** [comment]
@Dgadavin I just released a new gcdt version with the fix. Do you want to take a look?

**Comment by Dgadavin** [comment]
@markfink Yes. Sure. Thanks

**Comment by markfink** [comment]
feedback on slack was that it is ok now -> move to done...
